name: Hola mundo

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
      
      - name:  node version
        run: node --version
          