name: Hola mundo

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: hola mundo
        run: echo "Hola mundo desde la rama"

  other:
      needs: hola
      runs-on: ubuntu-latest

      steps:
        - name: hola mundo
          run: echo "Hola desde otro job desde la rama"