name: Hola mundo

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/actions/my-actions

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          message: "testing inputs"
      
      - name:  node version
        run: node --version
        