name: Hola mundo

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - 3306:3306  

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/actions/my-actions

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          message: "testing inputs"
      
      - name:  node version
        run: node --version
        